import type { Property } from "./types";

// Seeded from the real research in the acquisitions repo so the dashboard
// demonstrates every pipeline stage. Replaced by the Neon-backed store in M2.
export const SEED: Property[] = [
  {
    id: "inn-of-escalante",
    source: "search",
    url: "https://www.utahrealestate.com/2016474",
    name: "Inn of Escalante",
    address: "40 N 300 W",
    city: "Escalante",
    state: "UT",
    assetType: "motel",
    price: 715000,
    units: 8,
    yearBuilt: 1990,
    daysOnMarket: 540,
    priceCuts: "New low price (relisted from 2024)",
    sellerFinancing: false,
    driveHours: 2.5,
    stage: "outbox",
    fitScore: 9,
    contact: {
      name: "Denise Olson",
      brokerage: "Trails End Real Estate",
      phone: "(435) 680-4663",
      confidence: "high",
      source: "MLS 2016474",
    },
    analysis: {
      noi: 70000,
      capRate: 0.098,
      capex: 25000,
      stabilizedNoi: 78000,
      offerPrice: 620000,
      offerYieldOnCost: 0.12,
      fitScore: 9,
      model: "claude-opus-4-8",
      generatedAt: "2026-06-29T00:00:00Z",
      summary:
        "Turnkey, furnished 8-key boutique inn between Bryce & Capitol Reef. Confirmed price-cut + relist (~1.5yr) = motivated. Genuinely passive. Offer below ask with seller carry to a ~12% yield on cost.",
      creativeTerms:
        "Seller carry: 12% down ($74.4K), seller note $545.6K @ 6%, interest-only 24 mo, 5-yr balloon, no prepay.",
      financing: [
        { label: "Seller carry (recommended)", price: 620000, downPct: 0.12, rate: 0.06, structure: "seller_carry", balloonYears: 5, monthlyDebtService: 2728 },
        { label: "Master lease + option", price: 650000, downPct: 0, rate: 0, structure: "master_lease", notes: "24-mo lease, option locked at $650K" },
      ],
      risks: ["Tertiary/remote market — illiquid on exit", "Seasonality (tourism)", "Confirm true ADR/occupancy in DD"],
    },
    offer: {
      recipient: "",
      subject: "Offer on the Inn of Escalante — flexible terms, fast close",
      emailBody:
        "Hi Denise,\n\nI'd like to make a serious offer on the Inn of Escalante. I'm a buy-and-hold operator focused on small turnkey lodging in the Bryce/Capitol Reef corridor, and this is exactly my profile.\n\nI know it's been on the market a while — I'd rather structure something clean than nickel-and-dime your seller. I can do a fair price with seller financing (real money down, a competitive rate, short balloon), or a lease-with-option if they'd prefer income now and a sale later.\n\nCould you send the trailing 12-month P&L, occupancy/ADR, and let me know whether the seller would consider carrying? I'll turn a written LOI around within 48 hours.\n\nZion Property Acquisitions · (435) 625-1668 · info@zionpropertyacquisitions.com",
      status: "draft",
    },
    createdAt: "2026-06-29T00:00:00Z",
  },
  {
    id: "antimony-rv-park",
    source: "search",
    url: "https://www.utahrealestate.com/50-N-MAIN-ST-ANTIMONY-UT-84712/2146733",
    name: "Antimony Mercantile, RV Park & Grill",
    address: "50 N Main St",
    city: "Antimony",
    state: "UT",
    assetType: "rv_park",
    price: 549000,
    units: 20,
    daysOnMarket: 730,
    priceCuts: "Re-listed across 3 MLS#s since Apr 2024",
    sellerFinancing: false,
    driveHours: 3,
    stage: "outbox",
    fitScore: 8,
    contact: { name: "Kacey Nielson", brokerage: "Coldwell Banker Preferred", phone: "(435) 893-5477", email: "kaceynielsonrealtor@gmail.com", confidence: "high" },
    analysis: {
      offerPrice: 450000, fitScore: 8, model: "claude-opus-4-8", generatedAt: "2026-06-29T00:00:00Z",
      summary: "RV park + cash-flowing mercantile & grill, rural lifestyle seller, re-listed/tired. Cold seller-carry candidate.",
      creativeTerms: "10% down ($45K), seller note $405K @ 6%, interest-only yr 1, 5-yr balloon.",
      financing: [{ label: "Seller carry", price: 450000, downPct: 0.1, rate: 0.06, structure: "seller_carry", balloonYears: 5, monthlyDebtService: 2025 }],
      risks: ["Owner-operator-dependent income", "Seasonal", "Value mercantile inventory at cost"],
    },
    offer: { recipient: "kaceynielsonrealtor@gmail.com", subject: "Local buyer for the Antimony RV Park & Mercantile — flexible terms", emailBody: "Hi Kacey, …", status: "draft" },
    createdAt: "2026-06-29T00:00:00Z",
  },
  {
    id: "holbrook-motel",
    source: "search",
    url: "https://www.bizbuysell.com/business-opportunity/price-reduced-independent-motel-with-property-in-holbrook-az/2403186/",
    name: "Independent Motel, Holbrook AZ",
    city: "Holbrook",
    state: "AZ",
    assetType: "motel",
    price: 499000,
    units: 35,
    yearBuilt: 1960,
    daysOnMarket: 200,
    priceCuts: "Price reduced from $599K",
    driveHours: 4.5,
    stage: "sent",
    fitScore: 8,
    contact: { name: "Kavita Purohit", brokerage: "River Brokers", phone: "(770) 415-9940", email: "kavita@riverbrokers.com", confidence: "high" },
    analysis: {
      offerPrice: 475000, fitScore: 8, model: "claude-opus-4-8", generatedAt: "2026-06-28T00:00:00Z",
      summary: "Renovated-2024, owner-operated Route 66 motel, already price-cutting. Full-price-for-terms play.",
      creativeTerms: "Near-ask price, ~5% down, seller carries balance, 5-yr balloon.",
      financing: [{ label: "Full price for terms", price: 475000, downPct: 0.05, rate: 0.065, structure: "seller_carry", balloonYears: 5 }],
      risks: ["Verify RE + business (not leased ground)", "1960 building condition"],
    },
    offer: { recipient: "kavita@riverbrokers.com", subject: "Full-price-friendly offer on the Holbrook motel — if seller carries", emailBody: "Hi Kavita, …", status: "sent", sentAt: "2026-06-29T18:00:00Z", resendId: "re_mock_123" },
    createdAt: "2026-06-28T00:00:00Z",
  },
  {
    id: "white-pine-hotel",
    source: "search",
    url: "https://www.loopnet.com/Listing/1301-Aultman-St-Ely-NV/31117105/",
    name: "White Pine Hotel + MHP, Ely NV",
    address: "1301 Aultman St",
    city: "Ely",
    state: "NV",
    assetType: "motel",
    price: 1545000,
    units: 29,
    daysOnMarket: 300,
    priceCuts: "Cut from $1.65M · 16.89% cap advertised",
    sellerFinancing: true,
    driveHours: 3.5,
    stage: "analyzed",
    fitScore: 9,
    contact: { name: "Mark Moattar", phone: "(775) 293-0003", confidence: "medium", source: "verify — no email found" },
    analysis: {
      noi: 236000, capRate: 0.1435, offerPrice: 1500000, fitScore: 9, model: "claude-opus-4-8", generatedAt: "2026-06-29T00:00:00Z",
      summary: "Advertised owner financing + stated 14.35% cap; bundle the adjacent 20-pad vacant MHP under one note.",
      creativeTerms: "Bundle hotel+MHP $1.5M, 10% down, seller note $1.35M @ 6.5%, IO yr 1, 5-yr balloon.",
      financing: [{ label: "Bundle seller carry", price: 1500000, downPct: 0.1, rate: 0.065, structure: "seller_carry", balloonYears: 5 }],
      risks: ["14.35% cap is stated — verify T-12", "Ely is remote"],
    },
    createdAt: "2026-06-29T00:00:00Z",
  },
  {
    id: "dixie-cove",
    source: "manual",
    url: "https://www.marcusmillichap.com/properties/152084",
    name: "Dixie Cove Student Housing",
    address: "233 S 1000 E",
    city: "St. George",
    state: "UT",
    assetType: "multifamily",
    price: 1450000,
    units: 23,
    sqft: 8904,
    yearBuilt: 1973,
    daysOnMarket: 160,
    priceCuts: "Cut $1.55M → $1.45M, then UNDER CONTRACT",
    driveHours: 0,
    stage: "archived",
    fitScore: 9,
    contact: { name: "Evan Clark / Jake Miles", brokerage: "Marcus & Millichap", phone: "(801) 736-2632", email: "Evan.Clark@marcusmillichap.com", confidence: "high" },
    analysis: {
      noi: 63900, capRate: 0.0412, capex: 100000, stabilizedNoi: 102300, offerPrice: 925000, offerYieldOnCost: 0.1,
      fitScore: 9, model: "claude-opus-4-8", generatedAt: "2026-06-29T00:00:00Z",
      summary: "Value-add / OZ student housing across from Utah Tech. Densify 23→40 beds at modest rents → 10-cap at ~$925K. WENT UNDER CONTRACT — backup only.",
      creativeTerms: "10% down, seller carry, IO ramp; or $0-down 100% carry at $1.05M.",
      financing: [
        { label: "10-cap value buy", price: 925000, downPct: 0.1, rate: 0.065, structure: "seller_carry", balloonYears: 7 },
        { label: "No money down", price: 1050000, downPct: 0, rate: 0.065, structure: "seller_carry", balloonYears: 7 },
      ],
      risks: ["UNDER CONTRACT (not closed) — backup only", "City occupancy ordinance gates densification", "1973 building"],
    },
    createdAt: "2026-06-25T00:00:00Z",
    notes: "Under contract at $1.45M as of 2026-06-30. Owner: Sheffield Properties LLC (Kaysville). Pursue as backup / direct-to-owner.",
  },
  {
    id: "kanab-rv-fresh",
    source: "alert",
    url: "https://www.crexi.com/",
    name: "RV Park near Kanab (alert hit)",
    city: "Kanab",
    state: "UT",
    assetType: "rv_park",
    price: 1200000,
    daysOnMarket: 5,
    priceCuts: "New listing",
    driveHours: 1.5,
    stage: "sourced",
    createdAt: "2026-06-30T00:00:00Z",
    notes: "Came in via Crexi saved-search alert email. Awaiting screen + enrichment.",
  },

  // --- Round 4 research leads (sourced; verify price/DOM/contact before offering) ---
  {
    id: "raindance-cedar-city",
    source: "search",
    url: "https://www.loopnet.com/Listing/434-S-Main-St-Cedar-City-UT/35584033/",
    name: "Raindance — car wash + laundromat + retail",
    address: "434 S Main St",
    city: "Cedar City",
    state: "UT",
    assetType: "retail",
    price: 889000,
    driveHours: 0.8,
    stage: "sourced",
    fitScore: 9,
    sellerFinancing: true,
    contact: { name: "Travis Parry", brokerage: "LINX Commercial", phone: "(435) 359-4901", email: "travis@linxcre.com", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "⚠ VERIFY: whole property SOLD 9/2025 for $889K; now re-marketed as 4 components by new owner (new roof Dec 2025). Seller financing; ~$5K/mo income; OZ. Splittable: self-serve CW $359K / laundromat $599K / retail $299K / auto CW $249K.",
  },
  {
    id: "place-kiva-motel-portfolio",
    source: "search",
    url: "https://www.crexi.com/properties/1525928",
    name: "Place Resort + Kiva Motel portfolio",
    city: "Pinetop / Show Low",
    state: "AZ",
    assetType: "motel",
    driveHours: 5,
    stage: "sourced",
    fitScore: 9,
    sellerFinancing: true,
    contact: { name: "PHC Hotel Advisors (Pro Hospitality Group)", brokerage: "via Crexi", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Listing title advertises 'Seller Carry Option'; broker calls assets mismanaged/underutilized (value-add). Kiva ~$75.6K/key. Ask if Kiva sells standalone.",
  },
  {
    id: "stagecoach-66-seligman",
    source: "search",
    url: "https://www.loopnet.com/Listing/21455-W-Route-66-Seligman-AZ/35237681/",
    name: "Stagecoach 66 Motel + restaurant/bar",
    address: "21455 W I-40 Business Loop",
    city: "Seligman",
    state: "AZ",
    assetType: "motel",
    units: 42,
    price: 1070000,
    priceCuts: "Reduced from $1.1M",
    driveHours: 2.8,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: true,
    contact: { name: "Marcus & Millichap Hospitality", source: "listing #169893", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "⚠ VERIFY: M&M listing URL now redirects to homepage (may be pulled/sold); snippets still show active. If live: confirmed cut + ~$500K-down owner-carry, turnkey. Open ~$800–850K seller-financed.",
  },
  {
    id: "pier-95-rv-bullhead",
    source: "search",
    url: "https://www.loopnet.com/Listing/1621-Highway-95-Bullhead-City-AZ/35846471/",
    name: "Pier 95 RV Park (riverfront)",
    address: "1621 Hwy 95",
    city: "Bullhead City",
    state: "AZ",
    assetType: "rv_park",
    price: 3600000,
    driveHours: 2.5,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: true,
    contact: { source: "LoopNet 35846471 / crexi #2171533", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "⚠ VERIFY LIVENESS: rvparkstore #2058769 shows EXPIRED (Nov 2023); newer LoopNet 35846471/Crexi appear relisted/active at $3.6M. Confirm before pursuing. $1.6M assumable @ 6%, 22-yr amort advertised.",
  },
  {
    id: "hurricane-9600sf-retail",
    source: "search",
    url: "https://www.amazinglistings.com/property/455_10123534-75-N-200-W-Hurricane-UT-84737",
    name: "9,600 SF freestanding retail building",
    address: "75 N 200 W",
    city: "Hurricane",
    state: "UT",
    assetType: "retail",
    sqft: 9600,
    price: 2299007,
    driveHours: 0.4,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: true,
    contact: { name: "Tammy Banks", brokerage: "Zion Luxury Properties (agent Julian Coiner)", phone: "(435) 463-5412", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE. Tenant TK Fitness month-to-month. Seller financing 15–20% down, 1–2 yrs, negotiable rate. ~25 min from St George.",
  },
  {
    id: "budget-motel-delta",
    source: "search",
    url: "https://www.loopnet.com/Listing/75-S-350-E-Delta-UT/35218782/",
    name: "Budget Motel (29-key)",
    address: "75 S 350 E",
    city: "Delta",
    state: "UT",
    assetType: "motel",
    units: 29,
    price: 3200000,
    driveHours: 2.6,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: true,
    contact: { name: "Peak Collective RE / KW Commercial", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "'Open to Seller Finance'; advertised 15.39% cap (verify). Interior-corridor value-add.",
  },
  {
    id: "chino-valley-rv-park",
    source: "search",
    url: "https://www.crexi.com/properties/AZ/Chino_Valley/RV-Parks",
    name: "Chino Valley 34-unit RV Park",
    city: "Chino Valley",
    state: "AZ",
    assetType: "rv_park",
    units: 34,
    price: 1095000,
    driveHours: 3.5,
    stage: "sourced",
    fitScore: 7,
    sellerFinancing: true,
    contact: { source: "confirm via Crexi", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFY 2026-07: price now ~$1,095,000 (not $649,900). 'Seller Financing' + 'Value-Add' advertised. Pull flyer for occupancy/lot rents/terms.",
  },
  {
    id: "manti-69-s-main-duplex",
    source: "search",
    url: "https://www.utahrealestate.com/2155897",
    name: "69 S Main St duplex (C-1)",
    address: "69 S Main St",
    city: "Manti",
    state: "UT",
    assetType: "multifamily",
    units: 2,
    price: 475000,
    driveHours: 3.5,
    stage: "sourced",
    fitScore: 8,
    contact: { source: "MLS 2155897 (LandWatch)", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Duplex (3/3 + 2/2), C-1 downtown-commercial mixed-use upside; Snow College minutes away. Ask if seller will carry.",
  },
  {
    id: "daves-boat-rv-storage-condos",
    source: "search",
    url: "https://davesboatandrvstorage.com/",
    name: "Dave's Boat & RV Storage condos",
    city: "Lake Havasu City",
    state: "AZ",
    assetType: "self_storage",
    price: 91000,
    driveHours: 2.75,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: true,
    contact: { phone: "(928) 732-4267", email: "davesboatandrvstorage@gmail.com", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "'We offer owner financing.' Storage condos $91K (14×50) to $183K (30×45) — own + lease out. 'Only a few units left.'",
  },
  {
    id: "richfield-self-storage",
    source: "search",
    url: "https://www.crexi.com/properties/UT/Richfield/Self-Storage",
    name: "Richfield Self-Storage (~30K SF)",
    city: "Richfield",
    state: "UT",
    assetType: "self_storage",
    sqft: 30000,
    price: 1788000,
    driveHours: 2.25,
    stage: "sourced",
    fitScore: 7,
    contact: { source: "CityFeet / LoopNet / Crexi", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "$1.788M @ 7.26% cap (verified). Turnkey/stabilized. Underwrite to 8.5–9% (~$1.45–1.55M) and ask 'why selling / will you carry?'",
  },

  // --- Round 5 verified-live NEW finds ---
  {
    id: "big-water-self-storage",
    source: "search",
    url: "https://www.rankinrealty.net/",
    name: "Big Water Self Storage (Lake Powell Boat Storage)",
    city: "Big Water",
    state: "UT",
    assetType: "self_storage",
    sqft: 21000,
    price: 429900,
    driveHours: 1.5,
    stage: "sourced",
    fitScore: 9,
    sellerFinancing: true,
    contact: { name: "Heather Rankin", brokerage: "Rankin Realty SW", phone: "(928) 691-6444", email: "heather@heatherrankin.net", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (page loads). Self-storage + U-Haul, 21K SF on 2.57 ac + on-site quarters. 'Seller financing available.' Low entry, ~1.5h. Call for down/rate/term.",
  },
  {
    id: "i15-storage-littlefield",
    source: "search",
    url: "https://www.argus-selfstorage.com/properties/arizona/i15-storage",
    name: "I-15 Storage (154 units)",
    address: "4028 E Farm Rd",
    city: "Littlefield",
    state: "AZ",
    assetType: "self_storage",
    sqft: 39138,
    price: 1350000,
    driveHours: 0.6,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "Darsh Desai", brokerage: "Gorden Group / Argus", phone: "(701) 405-3665", email: "darsh@gorden-group.com", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (Argus page loads, 'NEW'). ~90% occ, no local competition, ~40 min from St George. Broker marketing mentions 'creative financing' — confirm carry directly.",
  },
  {
    id: "cedar-409-s-300w",
    source: "search",
    url: "https://www.bhhsutah.com/listing/2159136-409-s-300-w-cedar-city-ut-84720",
    name: "409 S 300 W (income duplex/by-room)",
    address: "409 S 300 W",
    city: "Cedar City",
    state: "UT",
    assetType: "multifamily",
    daysOnMarket: 42,
    price: 419000,
    driveHours: 0.8,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "April Gates", brokerage: "ERA Brokers Consolidated", phone: "(435) 220-5340", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (BHHS loads), 42 DOM. Rental history on main + basement apartment; SUU by-room. Proven income.",
  },
  {
    id: "ephraim-135-w-100n",
    source: "search",
    url: "https://www.oldhousesusa.com/listing/1904-victorian-house-ephraim-utah-84627",
    name: "135 W 100 N — 1904 Victorian income compound (Snow College)",
    address: "135 W 100 N",
    city: "Ephraim",
    state: "UT",
    assetType: "multifamily",
    units: 3,
    price: 589900,
    driveHours: 3.2,
    stage: "sourced",
    fitScore: 7,
    contact: { name: "Tiffany Lancaster", brokerage: "Tru Agency Real Estate", phone: "(435) 224-4529", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (oldhousesusa loads). 3 income units (main 3/3 + studio + cabin), furnished former B&B, walk to Snow College. STR upside. Replaces the dead '193 N Main' triplex lead.",
  },
  {
    id: "cathedral-valley-inn-caineville",
    source: "search",
    url: "https://www.bizquest.com/business-for-sale/the-cathedral-valley-inn/BW2163374/",
    name: "Cathedral Valley Inn (16-room motel)",
    address: "25 UT-24",
    city: "Caineville",
    state: "UT",
    assetType: "motel",
    units: 16,
    price: 1000000,
    driveHours: 3.5,
    stage: "sourced",
    fitScore: 7,
    contact: { source: "BizQuest broker (BW2163374); commercialsearch listing", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Likely active (BizQuest + CommercialSearch load). 16 rm on 4.95 ac, renovated, pool/jacuzzi, seasonal. Near Capitol Reef/Torrey. Smallest-ticket motel.",
  },
  {
    id: "rodeway-inn-kanab",
    source: "search",
    url: "https://www.bizbuysell.com/business-real-estate-for-sale/rodeway-inn-39-room-hotel/2171551/",
    name: "Rodeway Inn (39-room hotel)",
    city: "Kanab",
    state: "UT",
    assetType: "motel",
    units: 39,
    price: 2890000,
    driveHours: 1.25,
    stage: "sourced",
    fitScore: 7,
    contact: { source: "NAI Global (1322419); BizBuySell 2171551; helloarti 68960", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Likely active (indexed BizBuySell/NAI/BizQuest). 39 rm, 3 ac, 19,500 SF, 'fully operational turn-key,' pool/spa. Closest major motel to St George (~1.25h) in Grand Circle corridor.",
  },
  {
    id: "san-juan-inn-mexican-hat",
    source: "search",
    url: "https://www.crexi.com/properties/1693766/utah-san-juan-inn-trading-post",
    name: "San Juan Inn & Trading Post (38 keys)",
    city: "Mexican Hat",
    state: "UT",
    assetType: "motel",
    units: 38,
    price: 3200000,
    driveHours: 4.75,
    stage: "sourced",
    fitScore: 6,
    contact: { name: "Kristy Wiser", brokerage: "Keller Williams", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "CONFIRMED ACTIVE (LoopNet dated Oct 21 2025). 38 keys + restaurant + liquor license + trading post income, 4.17 ac on San Juan River. Farther (~5h) but hard-verified.",
  },
  {
    id: "apache-junction-mhp",
    source: "search",
    url: "https://www.parkbrokerage.com/homes-for-sale/arizona-mobile-home-park/",
    name: "Apache Junction MHP (85% occ)",
    city: "Apache Junction",
    state: "AZ",
    assetType: "mobile_home_park",
    price: 1050000,
    driveHours: 5.5,
    stage: "sourced",
    fitScore: 7,
    sellerFinancing: true,
    contact: { name: "Park Brokerage Inc", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "TIER-A VERIFIED ACTIVE (parkbrokerage page loads). 'Seller financing available with terms.' 85% occ. Edge of radius (~5.5h, Phoenix east valley).",
  },
  {
    id: "navajo-county-mhp",
    source: "search",
    url: "https://www.mobilehomeparkstore.com/mobile-home-parks/7012157-arizona-mhp-for-sale-in-arizona",
    name: "Navajo County MHP (12 lots, 15.4% cap)",
    city: "Show Low / Holbrook area",
    state: "AZ",
    assetType: "mobile_home_park",
    units: 12,
    price: 600000,
    driveHours: 4.5,
    stage: "sourced",
    fitScore: 6,
    contact: { name: "Brian Glen", source: "via mobilehomeparkstore portal", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "TIER-A VERIFIED ACTIVE (MHParkStore loads, updated 4/21/26). 12 lots, 100% occ, NOI ~$92.4K (15.4% actual cap), all park-owned homes. Cash only.",
  },
  {
    id: "lv-2201-james-bilbray-fourplex",
    source: "search",
    url: "https://www.weichert.com/136261927/",
    name: "2201 James Bilbray Dr — fourplex",
    address: "2201 James Bilbray Dr",
    city: "Las Vegas",
    state: "NV",
    assetType: "multifamily",
    units: 4,
    price: 815000,
    priceCuts: "Cut from $830K",
    driveHours: 2,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "Chris Brown", brokerage: "Rothwell Gornt Companies", email: "chrisbrown22@gmail.com", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (Weichert loads). 4×(2/2), built 1998, renovated, 5.74% proforma cap, occupied. NW LV near Summerlin. Price already cut.",
  },
  {
    id: "lv-5245-golden-ln-fourplex",
    source: "search",
    url: "https://www.compass.com/listing/5245-golden-lane-las-vegas-nv-89119/1806052967446700473/",
    name: "5245 Golden Ln — fourplex (UNLV zip 89119)",
    address: "5245 Golden Ln",
    city: "Las Vegas",
    state: "NV",
    assetType: "multifamily",
    units: 4,
    price: 649000,
    driveHours: 2.1,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "Ryan Crighton", brokerage: "Rothwell Gornt Companies", phone: "(702) 932-8813", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Active relist (MLS 2777516; prior cycle sold $610K 5/2025). 89119 = UNLV zip; 2/1 + 3/1 units are by-room-able to students ($600–800/room). Verify current agent holds relist.",
  },
];
