import type { Property } from "./types";

// Seeded from the real research in the acquisitions repo so the dashboard
// demonstrates every pipeline stage. Replaced by the Neon-backed store in M2.
export const SEED: Property[] = [
  {
    id: "inn-of-escalante",
    source: "search",
    url: "https://www.utahrealestate.com/2016474",
    name: "Inn of Escalante",
    address: "40 N 300 W",
    city: "Escalante",
    state: "UT",
    assetType: "motel",
    price: 715000,
    units: 8,
    yearBuilt: 1990,
    daysOnMarket: 540,
    priceCuts: "New low price (relisted from 2024)",
    sellerFinancing: false,
    driveHours: 2.5,
    stage: "outbox",
    fitScore: 9,
    contact: {
      name: "Denise Olson",
      brokerage: "Trails End Real Estate",
      phone: "(435) 680-4663",
      confidence: "high",
      source: "MLS 2016474",
    },
    analysis: {
      noi: 70000,
      capRate: 0.098,
      capex: 25000,
      stabilizedNoi: 78000,
      offerPrice: 620000,
      offerYieldOnCost: 0.12,
      fitScore: 9,
      model: "claude-opus-4-8",
      generatedAt: "2026-06-29T00:00:00Z",
      summary:
        "Turnkey, furnished 8-key boutique inn between Bryce & Capitol Reef. Confirmed price-cut + relist (~1.5yr) = motivated. Genuinely passive. Offer below ask with seller carry to a ~12% yield on cost.",
      creativeTerms:
        "Seller carry: 12% down ($74.4K), seller note $545.6K @ 6%, interest-only 24 mo, 5-yr balloon, no prepay.",
      financing: [
        { label: "Seller carry (recommended)", price: 620000, downPct: 0.12, rate: 0.06, structure: "seller_carry", balloonYears: 5, monthlyDebtService: 2728 },
        { label: "Master lease + option", price: 650000, downPct: 0, rate: 0, structure: "master_lease", notes: "24-mo lease, option locked at $650K" },
      ],
      risks: ["Tertiary/remote market — illiquid on exit", "Seasonality (tourism)", "Confirm true ADR/occupancy in DD"],
    },
    offer: {
      recipient: "",
      subject: "Offer on the Inn of Escalante — flexible terms, fast close",
      emailBody:
        "Hi Denise,\n\nI'd like to make a serious offer on the Inn of Escalante. I'm a buy-and-hold operator focused on small turnkey lodging in the Bryce/Capitol Reef corridor, and this is exactly my profile.\n\nI know it's been on the market a while — I'd rather structure something clean than nickel-and-dime your seller. I can do a fair price with seller financing (real money down, a competitive rate, short balloon), or a lease-with-option if they'd prefer income now and a sale later.\n\nCould you send the trailing 12-month P&L, occupancy/ADR, and let me know whether the seller would consider carrying? I'll turn a written LOI around within 48 hours.\n\nZion Property Acquisitions · (435) 625-1668 · info@zionpropertyacquisitions.com",
      status: "draft",
    },
    createdAt: "2026-06-29T00:00:00Z",
  },
  {
    id: "antimony-rv-park",
    source: "search",
    url: "https://www.utahrealestate.com/50-N-MAIN-ST-ANTIMONY-UT-84712/2146733",
    name: "Antimony Mercantile, RV Park & Grill",
    address: "50 N Main St",
    city: "Antimony",
    state: "UT",
    assetType: "rv_park",
    price: 549000,
    units: 20,
    daysOnMarket: 730,
    priceCuts: "Re-listed across 3 MLS#s since Apr 2024",
    sellerFinancing: false,
    driveHours: 3,
    stage: "outbox",
    fitScore: 8,
    contact: { name: "Kacey Nielson", brokerage: "Coldwell Banker Preferred", phone: "(435) 893-5477", email: "kaceynielsonrealtor@gmail.com", confidence: "high" },
    analysis: {
      offerPrice: 450000, fitScore: 8, model: "claude-opus-4-8", generatedAt: "2026-06-29T00:00:00Z",
      summary: "RV park + cash-flowing mercantile & grill, rural lifestyle seller, re-listed/tired. Cold seller-carry candidate.",
      creativeTerms: "10% down ($45K), seller note $405K @ 6%, interest-only yr 1, 5-yr balloon.",
      financing: [{ label: "Seller carry", price: 450000, downPct: 0.1, rate: 0.06, structure: "seller_carry", balloonYears: 5, monthlyDebtService: 2025 }],
      risks: ["Owner-operator-dependent income", "Seasonal", "Value mercantile inventory at cost"],
    },
    offer: { recipient: "kaceynielsonrealtor@gmail.com", subject: "Local buyer for the Antimony RV Park & Mercantile — flexible terms", emailBody: "Hi Kacey, …", status: "draft" },
    createdAt: "2026-06-29T00:00:00Z",
  },
  {
    id: "holbrook-motel",
    source: "search",
    url: "https://www.bizbuysell.com/business-opportunity/price-reduced-independent-motel-with-property-in-holbrook-az/2403186/",
    name: "Independent Motel, Holbrook AZ",
    city: "Holbrook",
    state: "AZ",
    assetType: "motel",
    price: 499000,
    units: 35,
    yearBuilt: 1960,
    daysOnMarket: 200,
    priceCuts: "Price reduced from $599K",
    driveHours: 4.5,
    stage: "sent",
    fitScore: 8,
    contact: { name: "Kavita Purohit", brokerage: "River Brokers", phone: "(770) 415-9940", email: "kavita@riverbrokers.com", confidence: "high" },
    analysis: {
      offerPrice: 475000, fitScore: 8, model: "claude-opus-4-8", generatedAt: "2026-06-28T00:00:00Z",
      summary: "Renovated-2024, owner-operated Route 66 motel, already price-cutting. Full-price-for-terms play.",
      creativeTerms: "Near-ask price, ~5% down, seller carries balance, 5-yr balloon.",
      financing: [{ label: "Full price for terms", price: 475000, downPct: 0.05, rate: 0.065, structure: "seller_carry", balloonYears: 5 }],
      risks: ["Verify RE + business (not leased ground)", "1960 building condition"],
    },
    offer: { recipient: "kavita@riverbrokers.com", subject: "Full-price-friendly offer on the Holbrook motel — if seller carries", emailBody: "Hi Kavita, …", status: "sent", sentAt: "2026-06-29T18:00:00Z", resendId: "re_mock_123" },
    createdAt: "2026-06-28T00:00:00Z",
  },
  {
    id: "white-pine-hotel",
    source: "search",
    url: "https://www.loopnet.com/Listing/1301-Aultman-St-Ely-NV/31117105/",
    name: "White Pine Hotel + MHP, Ely NV",
    address: "1301 Aultman St",
    city: "Ely",
    state: "NV",
    assetType: "motel",
    price: 1650000,
    units: 29,
    daysOnMarket: 300,
    sellerFinancing: true,
    driveHours: 3.5,
    stage: "analyzed",
    fitScore: 9,
    contact: { name: "Mark Moattar", phone: "(775) 293-0003", confidence: "medium", source: "verify — no email found" },
    analysis: {
      noi: 236000, capRate: 0.1435, offerPrice: 1500000, fitScore: 9, model: "claude-opus-4-8", generatedAt: "2026-06-29T00:00:00Z",
      summary: "Advertised owner financing + stated 14.35% cap; bundle the adjacent 20-pad vacant MHP under one note.",
      creativeTerms: "Bundle hotel+MHP $1.5M, 10% down, seller note $1.35M @ 6.5%, IO yr 1, 5-yr balloon.",
      financing: [{ label: "Bundle seller carry", price: 1500000, downPct: 0.1, rate: 0.065, structure: "seller_carry", balloonYears: 5 }],
      risks: ["14.35% cap is stated — verify T-12", "Ely is remote"],
    },
    createdAt: "2026-06-29T00:00:00Z",
  },
  {
    id: "dixie-cove",
    source: "manual",
    url: "https://www.marcusmillichap.com/properties/152084",
    name: "Dixie Cove Student Housing",
    address: "233 S 1000 E",
    city: "St. George",
    state: "UT",
    assetType: "multifamily",
    price: 1450000,
    units: 23,
    sqft: 8904,
    yearBuilt: 1973,
    daysOnMarket: 160,
    priceCuts: "Cut $1.55M → $1.45M, then UNDER CONTRACT",
    driveHours: 0,
    stage: "archived",
    fitScore: 9,
    contact: { name: "Evan Clark / Jake Miles", brokerage: "Marcus & Millichap", phone: "(801) 736-2632", email: "Evan.Clark@marcusmillichap.com", confidence: "high" },
    analysis: {
      noi: 63900, capRate: 0.0412, capex: 100000, stabilizedNoi: 102300, offerPrice: 925000, offerYieldOnCost: 0.1,
      fitScore: 9, model: "claude-opus-4-8", generatedAt: "2026-06-29T00:00:00Z",
      summary: "Value-add / OZ student housing across from Utah Tech. Densify 23→40 beds at modest rents → 10-cap at ~$925K. WENT UNDER CONTRACT — backup only.",
      creativeTerms: "10% down, seller carry, IO ramp; or $0-down 100% carry at $1.05M.",
      financing: [
        { label: "10-cap value buy", price: 925000, downPct: 0.1, rate: 0.065, structure: "seller_carry", balloonYears: 7 },
        { label: "No money down", price: 1050000, downPct: 0, rate: 0.065, structure: "seller_carry", balloonYears: 7 },
      ],
      risks: ["UNDER CONTRACT (not closed) — backup only", "City occupancy ordinance gates densification", "1973 building"],
    },
    createdAt: "2026-06-25T00:00:00Z",
    notes: "Under contract at $1.45M as of 2026-06-30. Owner: Sheffield Properties LLC (Kaysville). Pursue as backup / direct-to-owner.",
  },
  {
    id: "kanab-rv-fresh",
    source: "alert",
    url: "https://www.crexi.com/",
    name: "RV Park near Kanab (alert hit)",
    city: "Kanab",
    state: "UT",
    assetType: "rv_park",
    price: 1200000,
    daysOnMarket: 5,
    priceCuts: "New listing",
    driveHours: 1.5,
    stage: "sourced",
    createdAt: "2026-06-30T00:00:00Z",
    notes: "Came in via Crexi saved-search alert email. Awaiting screen + enrichment.",
  },
];
