import type { Property } from "./types";

// Seeded from the real research in the acquisitions repo so the dashboard
// demonstrates every pipeline stage. Replaced by the Neon-backed store in M2.
export const SEED: Property[] = [
  {
    id: "inn-of-escalante",
    source: "search",
    url: "https://www.utahrealestate.com/2016474",
    name: "Inn of Escalante",
    address: "40 N 300 W",
    city: "Escalante",
    state: "UT",
    assetType: "motel",
    price: 715000,
    units: 8,
    yearBuilt: 1990,
    daysOnMarket: 540,
    priceCuts: "⚠ LIKELY EXPIRED — URE MLS 2016474 returns 'not found in system' (2026-07-01 audit)",
    sellerFinancing: false,
    driveHours: 2.5,
    stage: "sourced",
    fitScore: 9,
    notes: "⚠ HOLD OFFER (2026-07-01 audit): URE listing 2016474 returns 'not found in the system' via proxy → likely expired/withdrawn. Still indexed at $715K + LoopNet mirrors 17171418/29101108 exist but unconfirmed. Century21/BHHS entries reference a DIFFERENT MLS (24-253471), tagged rental. Call Denise Olson / Trails End (435) 680-4663 to confirm active BEFORE sending the drafted offer.",
    contact: {
      name: "Denise Olson",
      brokerage: "Trails End Real Estate",
      phone: "(435) 680-4663",
      confidence: "high",
      source: "MLS 2016474",
    },
    analysis: {
      noi: 70000,
      capRate: 0.098,
      capex: 25000,
      stabilizedNoi: 78000,
      offerPrice: 620000,
      offerYieldOnCost: 0.12,
      fitScore: 9,
      model: "claude-opus-4-8",
      generatedAt: "2026-06-29T00:00:00Z",
      summary:
        "Turnkey, furnished 8-key boutique inn between Bryce & Capitol Reef. Confirmed price-cut + relist (~1.5yr) = motivated. Genuinely passive. Offer below ask with seller carry to a ~12% yield on cost.",
      creativeTerms:
        "Seller carry: 12% down ($74.4K), seller note $545.6K @ 6%, interest-only 24 mo, 5-yr balloon, no prepay.",
      financing: [
        { label: "Seller carry (recommended)", price: 620000, downPct: 0.12, rate: 0.06, structure: "seller_carry", balloonYears: 5, monthlyDebtService: 2728 },
        { label: "Master lease + option", price: 650000, downPct: 0, rate: 0, structure: "master_lease", notes: "24-mo lease, option locked at $650K" },
      ],
      risks: ["Tertiary/remote market — illiquid on exit", "Seasonality (tourism)", "Confirm true ADR/occupancy in DD"],
    },
    offer: {
      recipient: "",
      subject: "Offer on the Inn of Escalante — flexible terms, fast close",
      emailBody:
        "Hi Denise,\n\nI'd like to make a serious offer on the Inn of Escalante. I'm a buy-and-hold operator focused on small turnkey lodging in the Bryce/Capitol Reef corridor, and this is exactly my profile.\n\nI know it's been on the market a while — I'd rather structure something clean than nickel-and-dime your seller. I can do a fair price with seller financing (real money down, a competitive rate, short balloon), or a lease-with-option if they'd prefer income now and a sale later.\n\nCould you send the trailing 12-month P&L, occupancy/ADR, and let me know whether the seller would consider carrying? I'll turn a written LOI around within 48 hours.\n\nZion Property Acquisitions · (435) 625-1668 · info@zionpropertyacquisitions.com",
      status: "draft",
    },
    createdAt: "2026-06-29T00:00:00Z",
  },
  {
    id: "antimony-rv-park",
    source: "search",
    url: "https://www.utahrealestate.com/50-N-MAIN-ST-ANTIMONY-UT-84712/2146733",
    name: "Antimony Mercantile, RV Park & Grill",
    address: "50 N Main St",
    city: "Antimony",
    state: "UT",
    assetType: "rv_park",
    price: 549000,
    units: 20,
    daysOnMarket: 93,
    priceCuts: "Re-listed across 3 MLS#s since Apr 2024; current URE listing 93 DOM (2026-07-01 audit, confirmed active $549K)",
    sellerFinancing: false,
    driveHours: 3,
    stage: "outbox",
    fitScore: 8,
    contact: { name: "Kacey Nielson", brokerage: "Coldwell Banker Preferred", phone: "(435) 893-5477", email: "kaceynielsonrealtor@gmail.com", confidence: "high" },
    analysis: {
      offerPrice: 450000, fitScore: 8, model: "claude-opus-4-8", generatedAt: "2026-06-29T00:00:00Z",
      summary: "RV park + cash-flowing mercantile & grill, rural lifestyle seller, re-listed/tired. Cold seller-carry candidate.",
      creativeTerms: "10% down ($45K), seller note $405K @ 6%, interest-only yr 1, 5-yr balloon.",
      financing: [{ label: "Seller carry", price: 450000, downPct: 0.1, rate: 0.06, structure: "seller_carry", balloonYears: 5, monthlyDebtService: 2025 }],
      risks: ["Owner-operator-dependent income", "Seasonal", "Value mercantile inventory at cost"],
    },
    offer: { recipient: "kaceynielsonrealtor@gmail.com", subject: "Local buyer for the Antimony RV Park & Mercantile — flexible terms", emailBody: "Hi Kacey, …", status: "draft" },
    createdAt: "2026-06-29T00:00:00Z",
  },
  {
    id: "holbrook-motel",
    source: "search",
    url: "https://www.bizbuysell.com/business-opportunity/price-reduced-independent-motel-with-property-in-holbrook-az/2403186/",
    name: "Independent Motel, Holbrook AZ",
    city: "Holbrook",
    state: "AZ",
    assetType: "motel",
    price: 699000,
    units: 35,
    yearBuilt: 1960,
    daysOnMarket: 200,
    priceCuts: "⚠ Live BizBuySell now ~$699K (2026-07-01 audit) — sent offer of $475K was based on stale $499K",
    driveHours: 4.5,
    stage: "sent",
    fitScore: 8,
    contact: { name: "Kavita Purohit", brokerage: "River Brokers", phone: "(770) 415-9940", email: "kavita@riverbrokers.com", confidence: "high" },
    analysis: {
      offerPrice: 475000, fitScore: 8, model: "claude-opus-4-8", generatedAt: "2026-06-28T00:00:00Z",
      summary: "Renovated-2024, owner-operated Route 66 motel, already price-cutting. Full-price-for-terms play.",
      creativeTerms: "Near-ask price, ~5% down, seller carries balance, 5-yr balloon.",
      financing: [{ label: "Full price for terms", price: 475000, downPct: 0.05, rate: 0.065, structure: "seller_carry", balloonYears: 5 }],
      risks: ["Verify RE + business (not leased ground)", "1960 building condition"],
    },
    offer: { recipient: "kavita@riverbrokers.com", subject: "Full-price-friendly offer on the Holbrook motel — if seller carries", emailBody: "Hi Kavita, …", status: "sent", sentAt: "2026-06-29T18:00:00Z", resendId: "re_mock_123" },
    createdAt: "2026-06-28T00:00:00Z",
  },
  {
    id: "white-pine-hotel",
    source: "search",
    url: "https://www.loopnet.com/Listing/1301-Aultman-St-Ely-NV/31117105/",
    name: "White Pine Hotel + MHP, Ely NV",
    address: "1301 Aultman St",
    city: "Ely",
    state: "NV",
    assetType: "motel",
    price: 1400000,
    units: 29,
    daysOnMarket: 300,
    priceCuts: "Cut $1.65M → ~$1.4M · 18.64% cap advertised (2026-07-01 audit)",
    sellerFinancing: true,
    driveHours: 3.5,
    stage: "analyzed",
    fitScore: 9,
    contact: { name: "Mark Moattar", phone: "(775) 293-0003", confidence: "medium", source: "verify — no email found" },
    analysis: {
      noi: 236000, capRate: 0.1864, offerPrice: 1300000, fitScore: 9, model: "claude-opus-4-8", generatedAt: "2026-06-29T00:00:00Z",
      summary: "LoopNet 31117105 live at ~$1.4M / 18.64% cap advertised; bundle the adjacent MHP (2.4ac, 10 rented / 30 spaces) under one note. Owner financing was advertised earlier but is NOT confirmed on the current live page — verify.",
      creativeTerms: "Bundle hotel+MHP ~$1.3M, 10% down, seller note ~$1.17M @ 6.5%, IO yr 1, 5-yr balloon (if seller carries).",
      financing: [{ label: "Bundle seller carry", price: 1300000, downPct: 0.1, rate: 0.065, structure: "seller_carry", balloonYears: 5 }],
      risks: ["18.64% cap is stated — verify T-12", "Owner financing UNCONFIRMED on current live LoopNet page", "Crexi 1714287 now 404 (dead)", "Ely is remote"],
    },
    createdAt: "2026-06-29T00:00:00Z",
  },
  {
    id: "dixie-cove",
    source: "manual",
    url: "https://www.marcusmillichap.com/properties/152084",
    name: "Dixie Cove Student Housing",
    address: "233 S 1000 E",
    city: "St. George",
    state: "UT",
    assetType: "multifamily",
    price: 1450000,
    units: 23,
    sqft: 8904,
    yearBuilt: 1973,
    daysOnMarket: 160,
    priceCuts: "Cut $1.55M → $1.45M, then UNDER CONTRACT",
    driveHours: 0,
    stage: "archived",
    fitScore: 9,
    contact: { name: "Evan Clark / Jake Miles", brokerage: "Marcus & Millichap", phone: "(801) 736-2632", email: "Evan.Clark@marcusmillichap.com", confidence: "high" },
    analysis: {
      noi: 63900, capRate: 0.0412, capex: 100000, stabilizedNoi: 102300, offerPrice: 925000, offerYieldOnCost: 0.1,
      fitScore: 9, model: "claude-opus-4-8", generatedAt: "2026-06-29T00:00:00Z",
      summary: "Value-add / OZ student housing across from Utah Tech. Densify 23→40 beds at modest rents → 10-cap at ~$925K. WENT UNDER CONTRACT — backup only.",
      creativeTerms: "10% down, seller carry, IO ramp; or $0-down 100% carry at $1.05M.",
      financing: [
        { label: "10-cap value buy", price: 925000, downPct: 0.1, rate: 0.065, structure: "seller_carry", balloonYears: 7 },
        { label: "No money down", price: 1050000, downPct: 0, rate: 0.065, structure: "seller_carry", balloonYears: 7 },
      ],
      risks: ["UNDER CONTRACT (not closed) — backup only", "City occupancy ordinance gates densification", "1973 building"],
    },
    createdAt: "2026-06-25T00:00:00Z",
    notes: "Under contract at $1.45M as of 2026-06-30. Owner: Sheffield Properties LLC (Kaysville). Pursue as backup / direct-to-owner.",
  },
  {
    id: "kanab-rv-fresh",
    source: "alert",
    url: "https://www.crexi.com/",
    name: "RV Park near Kanab (alert hit)",
    city: "Kanab",
    state: "UT",
    assetType: "rv_park",
    price: 1200000,
    daysOnMarket: 5,
    priceCuts: "New listing",
    driveHours: 1.5,
    stage: "sourced",
    createdAt: "2026-06-30T00:00:00Z",
    notes: "Came in via Crexi saved-search alert email. Awaiting screen + enrichment.",
  },

  // --- Round 4 research leads (sourced; verify price/DOM/contact before offering) ---
  // REMOVED 2026-07-01 audit (confirmed dead): raindance-cedar-city ($889K listing 410-Gone,
  // no component listings exist), place-kiva-motel-portfolio (Crexi "listing removed"),
  // stagecoach-66-seligman (M&M listing pulled, FB "Closing Soon", likely sold).
  {
    id: "pier-95-rv-bullhead",
    source: "search",
    url: "https://www.crexi.com/properties/2171533/arizona-pier-95-rv-park",
    name: "Pier 95 RV Park (riverfront)",
    address: "1621 Hwy 95",
    city: "Bullhead City",
    state: "AZ",
    assetType: "rv_park",
    price: 2750000,
    priceCuts: "Cut from $3.6M → $2.75M (2026-07-01 audit)",
    driveHours: 2.5,
    stage: "sourced",
    fitScore: 9,
    sellerFinancing: true,
    contact: { name: "Clay Merrigan", brokerage: "Country Ranch Realty", source: "Crexi 2171533", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "✅ VERIFIED ACTIVE (2026-07-01 audit): Crexi 2171533 live, 'updated 6 days ago', 292 DOM, repriced $3.6M → $2.75M. 3.65ac riverfront, ~27-30 spaces, zoned 50+. Assumable owner-carry ~$1.5M @ 6% CONFIRMED on live page. Old rvparkstore 2058769 = expired Nov 2023 (ignore).",
  },
  {
    id: "hurricane-9600sf-retail",
    source: "search",
    url: "https://www.amazinglistings.com/property/455_10123534-75-N-200-W-Hurricane-UT-84737",
    name: "9,600 SF freestanding retail building",
    address: "75 N 200 W",
    city: "Hurricane",
    state: "UT",
    assetType: "retail",
    sqft: 9600,
    price: 2299007,
    driveHours: 0.4,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: true,
    contact: { name: "Tammy Banks", brokerage: "Zion Luxury Properties (agent Julian Coiner)", phone: "(435) 463-5412", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (2026-07-01 audit — amazinglistings page loads, $2,299,007). Tenant TK Fitness month-to-month. ⚠ Seller financing (15–20% down, 1–2 yrs) is OM/verbal — NOT shown on the live listing page; confirm with agent. ~25 min from St George.",
  },
  {
    id: "budget-motel-delta",
    source: "search",
    url: "https://www.loopnet.com/Listing/75-S-350-E-Delta-UT/35218782/",
    name: "Budget Motel (29-key)",
    address: "75 S 350 E",
    city: "Delta",
    state: "UT",
    assetType: "motel",
    units: 29,
    price: 4000000,
    driveHours: 2.6,
    stage: "sourced",
    fitScore: 7,
    sellerFinancing: true,
    contact: { name: "Peak Collective RE / KW Commercial", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "⚠ REPRICED UP to $4.0M (2026-07-01 audit; was $3.2M). Active on LoopNet 35218782, 15.39% cap advertised. 'Open to Seller Finance' NOT confirmed on current live page. Interior-corridor value-add — but higher basis dents the thesis.",
  },
  {
    id: "chino-valley-rv-park",
    source: "search",
    url: "https://www.crexi.com/properties/AZ/Chino_Valley/RV-Parks",
    name: "Chino Valley 34-unit RV Park",
    city: "Chino Valley",
    state: "AZ",
    assetType: "rv_park",
    units: 34,
    price: 1095000,
    driveHours: 3.5,
    stage: "sourced",
    fitScore: 7,
    sellerFinancing: true,
    contact: { source: "confirm via Crexi", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Active + 'Seller Financing' + 'Value-Add' CONFIRMED on Crexi (2026-07-01 audit), but ⚠ PRICE UNRESOLVED: cached snippets show both $1,095,000 and $649,900 and Crexi blocks the detail page — open in browser to read live price + agent. Pull flyer for occupancy/lot rents/terms.",
  },
  {
    id: "manti-69-s-main-duplex",
    source: "search",
    url: "https://www.utahrealestate.com/2155897",
    name: "69 S Main St duplex (C-1)",
    address: "69 S Main St",
    city: "Manti",
    state: "UT",
    assetType: "multifamily",
    units: 2,
    price: 475000,
    driveHours: 3.5,
    stage: "sourced",
    fitScore: 8,
    contact: { source: "MLS 2155897 (LandWatch)", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE $475K (2026-07-01 audit — redsign + homes.com, MLS 2155897, ERA Brokers Richfield). C-1 downtown-commercial mixed-use, 5bd/5ba 4,299 SF; Snow College minutes away. Note an OLDER stale MLS 2020314 @ $449,900 (Donavan/Tyson) = prior cycle, ignore. Ask if seller will carry.",
  },
  {
    id: "daves-boat-rv-storage-condos",
    source: "search",
    url: "https://davesboatandrvstorage.com/",
    name: "Dave's Boat & RV Storage condos",
    city: "Lake Havasu City",
    state: "AZ",
    assetType: "self_storage",
    price: 91000,
    driveHours: 2.75,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: true,
    contact: { phone: "(928) 732-4267", email: "davesboatandrvstorage@gmail.com", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "'We offer owner financing.' Storage condos $91K (14×50) to $183K (30×45) — own + lease out. 'Only a few units left.'",
  },
  {
    id: "richfield-self-storage",
    source: "search",
    url: "https://www.crexi.com/properties/UT/Richfield/Self-Storage",
    name: "Richfield Self-Storage (~30K SF)",
    city: "Richfield",
    state: "UT",
    assetType: "self_storage",
    sqft: 30000,
    price: 1788000,
    driveHours: 2.25,
    stage: "sourced",
    fitScore: 7,
    contact: { source: "CityFeet / LoopNet / Crexi", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Active, $1.788M @ 7.26% cap (2026-07-01 audit — confirmed via CityFeet/Crexi snippets). ⚠ Listing agent still not surfaced (both portals block detail) — open in browser to capture broker. Turnkey/stabilized. Underwrite to 8.5–9% (~$1.45–1.55M) and ask 'why selling / will you carry?'",
  },

  // --- Round 5 verified-live NEW finds ---
  {
    id: "big-water-self-storage",
    source: "search",
    url: "https://www.rankinrealty.net/",
    name: "Big Water Self Storage (Lake Powell Boat Storage)",
    city: "Big Water",
    state: "UT",
    assetType: "self_storage",
    sqft: 21000,
    price: 429900,
    driveHours: 1.5,
    stage: "sourced",
    fitScore: 9,
    sellerFinancing: true,
    contact: { name: "Heather Rankin", brokerage: "Rankin Realty SW", phone: "(928) 691-6444", email: "heather@heatherrankin.net", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (page loads). Self-storage + U-Haul, 21K SF on 2.57 ac + on-site quarters. 'Seller financing available.' Low entry, ~1.5h. Call for down/rate/term.",
  },
  {
    id: "i15-storage-littlefield",
    source: "search",
    url: "https://www.argus-selfstorage.com/properties/arizona/i15-storage",
    name: "I-15 Storage (154 units)",
    address: "4028 E Farm Rd",
    city: "Littlefield",
    state: "AZ",
    assetType: "self_storage",
    sqft: 39138,
    price: 1350000,
    driveHours: 0.6,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "Darsh Desai", brokerage: "Gorden Group / Argus", phone: "(701) 405-3665", email: "darsh@gorden-group.com", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (Argus page loads, 'NEW'). ~90% occ, no local competition, ~40 min from St George. Broker marketing mentions 'creative financing' — confirm carry directly.",
  },
  {
    id: "cedar-409-s-300w",
    source: "search",
    url: "https://www.bhhsutah.com/listing/2159136-409-s-300-w-cedar-city-ut-84720",
    name: "409 S 300 W (income duplex/by-room)",
    address: "409 S 300 W",
    city: "Cedar City",
    state: "UT",
    assetType: "multifamily",
    daysOnMarket: 42,
    price: 419000,
    driveHours: 0.8,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "April Gates", brokerage: "ERA Brokers Consolidated", phone: "(435) 220-5340", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (BHHS loads), 42 DOM. Rental history on main + basement apartment; SUU by-room. Proven income.",
  },
  {
    id: "ephraim-135-w-100n",
    source: "search",
    url: "https://www.oldhousesusa.com/listing/1904-victorian-house-ephraim-utah-84627",
    name: "135 W 100 N — 1904 Victorian income compound (Snow College)",
    address: "135 W 100 N",
    city: "Ephraim",
    state: "UT",
    assetType: "multifamily",
    units: 3,
    price: 589900,
    driveHours: 3.2,
    stage: "sourced",
    fitScore: 7,
    contact: { name: "Tiffany Lancaster", brokerage: "Tru Agency Real Estate", phone: "(435) 224-4529", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "VERIFIED ACTIVE (oldhousesusa loads). 3 income units (main 3/3 + studio + cabin), furnished former B&B, walk to Snow College. STR upside. Replaces the dead '193 N Main' triplex lead.",
  },
  {
    id: "cathedral-valley-inn-caineville",
    source: "search",
    url: "https://www.bizquest.com/business-for-sale/the-cathedral-valley-inn/BW2163374/",
    name: "Cathedral Valley Inn (16-room motel)",
    address: "25 UT-24",
    city: "Caineville",
    state: "UT",
    assetType: "motel",
    units: 16,
    price: 1000000,
    driveHours: 3.5,
    stage: "sourced",
    fitScore: 7,
    contact: { source: "BizQuest broker (BW2163374); commercialsearch listing", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "⚠ UNVERIFIABLE (2026-07-01 audit): BizQuest BW2163374 403'd on direct fetch AND proxy; indexed at $1M (16 rm, renovated, pool/jacuzzi, seasonal, near Capitol Reef/Torrey) but no listing page would load to confirm it isn't sold/pending. Open BizQuest in a browser or call to confirm.",
  },
  {
    id: "rodeway-inn-kanab",
    source: "search",
    url: "https://www.bizbuysell.com/business-real-estate-for-sale/rodeway-inn-39-room-hotel/2171551/",
    name: "Rodeway Inn (39-room hotel)",
    city: "Kanab",
    state: "UT",
    assetType: "motel",
    units: 39,
    price: 2890000,
    driveHours: 1.25,
    stage: "sourced",
    fitScore: 7,
    contact: { source: "NAI Global (1322419); BizBuySell 2171551; helloarti 68960", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "⚠ UNVERIFIABLE (2026-07-01 audit): BizBuySell 2171551 / NAI 1322419 / helloarti all 403/cookie-walled on fetch + proxy. Indexed (39 rm, 3 ac, 19,500 SF, turn-key, pool/spa) but no page loaded to confirm price (~$2.89M) or active status. Closest major motel to St George (~1.25h). Open in browser / call NAI Global to confirm.",
  },
  // REMOVED 2026-07-01 audit: san-juan-inn-mexican-hat — Crexi 1693766 now off-market/unpriced
  // (was $3.2M); DOM locked. Do not treat as live.
  {
    id: "apache-junction-mhp",
    source: "search",
    url: "https://www.parkbrokerage.com/homes-for-sale/arizona-mobile-home-park/",
    name: "Apache Junction MHP (85% occ)",
    city: "Apache Junction",
    state: "AZ",
    assetType: "mobile_home_park",
    price: 1050000,
    driveHours: 5.5,
    stage: "sourced",
    fitScore: 7,
    sellerFinancing: true,
    contact: { name: "Park Brokerage Inc", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "⚠ VERIFY BY CALL (2026-07-01 audit): parkbrokerage page loads + markets it ('seller financing with terms', 85% occ), BUT the site renders every property (incl. clearly-SOLD parks) with 'recent sale' language, so active-vs-sold can't be confirmed online. Don't confuse with SOLD Apache Palms ($1.5M) / Globe Apache ($1.2M). Edge of radius (~5.5h).",
  },
  {
    id: "navajo-county-mhp",
    source: "search",
    url: "https://www.mobilehomeparkstore.com/mobile-home-parks/7012157-arizona-mhp-for-sale-in-arizona",
    name: "Navajo County MHP (12 lots, 15.4% cap)",
    city: "Show Low / Holbrook area",
    state: "AZ",
    assetType: "mobile_home_park",
    units: 12,
    price: 600000,
    driveHours: 4.5,
    stage: "sourced",
    fitScore: 6,
    contact: { name: "Brian Glen", source: "via mobilehomeparkstore portal", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "TIER-A VERIFIED ACTIVE (MHParkStore loads, updated 4/21/26). 12 lots, 100% occ, NOI ~$92.4K (15.4% actual cap), all park-owned homes. Cash only.",
  },
  {
    id: "lv-2201-james-bilbray-fourplex",
    source: "search",
    url: "https://www.weichert.com/136261927/",
    name: "2201 James Bilbray Dr — fourplex",
    address: "2201 James Bilbray Dr",
    city: "Las Vegas",
    state: "NV",
    assetType: "multifamily",
    units: 4,
    price: 815000,
    priceCuts: "Cut from $830K",
    driveHours: 2,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "Chris Brown", brokerage: "Rothwell Gornt Companies", email: "chrisbrown22@gmail.com", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "✅ VERIFIED ACTIVE $815K, DOM 0 fresh relist (2026-07-01 audit — Weichert loads; other portals stale ~$842K). 4×(2/2), built 1998, renovated, occupied, HOA w/ pool. Zip 89108 = NW LV/Summerlin (NOT a UNLV zip — whole-unit rental, not by-room). 5.74% cap is from prior marketing, not on live page.",
  },
  {
    id: "lv-5245-golden-ln-fourplex",
    source: "search",
    url: "https://www.compass.com/listing/5245-golden-lane-las-vegas-nv-89119/1806052967446700473/",
    name: "5245 Golden Ln — fourplex (UNLV zip 89119)",
    address: "5245 Golden Ln",
    city: "Las Vegas",
    state: "NV",
    assetType: "multifamily",
    units: 4,
    price: 649000,
    driveHours: 2.1,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "Ryan Crighton", brokerage: "Rothwell Gornt Companies", phone: "(702) 932-8813", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "✅ VERIFIED ACTIVE RELIST $649K (2026-07-01 audit): MLS 2777516 is a genuine distinct current listing — NOT the old sold record (MLS 2668726 CLOSED $610K 5/8/25). 89119 = UNLV zip; 2/1 + 3/1 units by-room-able to students ($600–800/room). Relist agent unverified (Zillow CAPTCHA) — call Ryan Crighton (702) 932-8813 to confirm he holds it.",
  },

  // --- Round 6 NEW verified-live finds (2026-07-01 audit) ---
  {
    id: "university-lofts-cedar-city",
    source: "search",
    url: "https://www.zillow.com/b/university-lofts-student-housing-cedar-city-ut-CjmhPF/",
    name: "University Lofts – Building B (52-bed SUU student housing)",
    address: "119 N 800 W",
    city: "Cedar City",
    state: "UT",
    assetType: "multifamily",
    units: 7,
    beds: 52,
    price: 3799000,
    driveHours: 0.8,
    stage: "sourced",
    fitScore: 9,
    contact: { source: "Crexi Cedar City multifamily (agent not surfaced — pull from live listing)", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "✅ ACTIVE (2026-07-01 audit — Zillow + Homes.com building pages load). Purpose-built student complex 7 units / 52 bed / 52 bath, ~1 block from SUU, described 100% occupied (immediate cash flow). Best pure buy-box fit (turnkey by-room student housing, not a rehab) but largest ticket. Agent/DOM not extractable — reopen Crexi live before contact.",
  },
  {
    id: "5-star-inn-panguitch",
    source: "search",
    url: "https://www.bizquest.com/business-for-sale/5-star-rated-hotel-inn-and-restaurant/BW2497943/",
    name: "5-Star Inn & Restaurant, Panguitch",
    city: "Panguitch",
    state: "UT",
    assetType: "motel",
    units: 10,
    price: 900000,
    driveHours: 1.5,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "Phil Neuenswander", brokerage: "First Choice Business Brokers", phone: "(702) 355-2395", email: "philn@fcbb.com", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "✅ ACTIVE (2026-07-01 audit — BizQuest BW2497943, agent confirmed; NAI Excel corroborates 'Iconic Hotel in Panguitch'). ~10-room inn (only 6 rented) + restaurant on the highway to Bryce, open ~5 mo/yr — seller flags extending the season as 'an easy way to increase revenue.' 10-yr track record. Real estate available separately +$800K. Semi-passive with clear upside.",
  },
  {
    id: "quality-inn-beaver",
    source: "search",
    url: "https://www.crexi.com/properties/2436669/utah-quality-inn-beaver-i-15",
    name: "Quality Inn Beaver I-15 (48-key)",
    address: "626 W 1400 N",
    city: "Beaver",
    state: "UT",
    assetType: "motel",
    units: 48,
    price: 4800000,
    driveHours: 1.5,
    stage: "sourced",
    fitScore: 7,
    contact: { source: "Crexi 2436669 (agent not surfaced on county page)", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Active (2026-07-01 audit — surfaced on Crexi Beaver county page, ID 2436669). 48-key flagged interstate motel on I-15, ~1.5h N of St George. Larger than the small-motel target and full-franchise, but solid income hospitality. Reopen Crexi live for agent/DOM/price-cut history.",
  },
  {
    id: "the-lodge-hatch",
    source: "search",
    url: "https://www.highcountryrealty.net/search_piute_garfield.htm",
    name: "The Lodge, Hatch (Bryce gateway)",
    city: "Hatch",
    state: "UT",
    assetType: "motel",
    price: 1650000,
    driveHours: 1.5,
    stage: "sourced",
    fitScore: 7,
    contact: { name: "High Country Realty", source: "MLS 116791", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Active (2026-07-01 audit — High Country Realty listings page loads, MLS 116791). Small lodge/hospitality, 0.91 ac, built 1978, 'Gateway to Bryce Canyon,' ~1.5h from St George. No seller-financing note published — contact broker.",
  },
  {
    id: "maple-ave-mhrv-yuma",
    source: "search",
    url: "https://www.mobilehomeparkstore.com/mobile-home-parks/7046002-maple-avenue-mhrv-for-sale-in-yuma-az",
    name: "Maple Avenue MHRV (31-space MHP)",
    address: "1947 S Maple Ave",
    city: "Yuma",
    state: "AZ",
    assetType: "mobile_home_park",
    units: 31,
    price: 1180000,
    driveHours: 5.5,
    stage: "sourced",
    fitScore: 6,
    contact: { name: "Lane G. Neville / Stephen Yowell", brokerage: "NAI Horizon", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Active (2026-07-01 audit — MHParkStore 7046002 loads). 31 lots (all park-owned homes), avg lot rent $466, city water/sewer, 77.4% occ = value-add upside, in an Opportunity Zone. ⚠ Yuma is ~5.5h — at/just past the radius edge. No seller financing advertised.",
  },

  // --- Round 6 SINGLE-FAMILY STEALS (2026-07-01) — undervalued SFRs; ALL rents ESTIMATED, DOM mostly unconfirmed ---
  {
    id: "sfr-982-spruce-cedar",
    source: "search",
    url: "https://www.zillow.com/cedar-city-ut/price-reduced/",
    name: "982 Spruce St — 4bd SUU by-room steal",
    address: "982 Spruce St",
    city: "Cedar City",
    state: "UT",
    assetType: "house",
    beds: 4,
    sqft: 2384,
    price: 355000,
    priceCuts: "$53,500 cut (6/9) — biggest cut found; ~$149/sqft",
    driveHours: 0.8,
    stage: "sourced",
    fitScore: 8,
    contact: { name: "Matthew Bagley", brokerage: "ERA Realty Center", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "TOP SFR pick. 4/2, ~2,384 SF, near SUU → 4 rooms × ~$550 ≈ $2,200/mo by-room vs whole ~$2,000. ⚠ DATA CONFLICT: one feed showed $255K/2,459sf vs $355K/2,384sf — VERIFY price. A cut this size can signal deferred maintenance. Rents ESTIMATED; DOM unconfirmed.",
  },
  {
    id: "sfr-480-n-300w-cedar",
    source: "search",
    url: "https://www.coldwellbankerhomes.com/ut/cedar-city/",
    name: "480 N 300 W — 4bd best $/sqft (SUU)",
    address: "480 N 300 W",
    city: "Cedar City",
    state: "UT",
    assetType: "house",
    beds: 4,
    sqft: 2448,
    price: 359900,
    priceCuts: "~$147/sqft — below $429K median list",
    driveHours: 0.8,
    stage: "sourced",
    fitScore: 7,
    contact: { source: "Coldwell Banker (coldwellbankerhomes.com)", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "4/2, ~2,448 SF, ~$147/sqft (well under comps). SUU by-room: 4 × ~$550 ≈ $2,200/mo. No cut/DOM confirmed. Verify age/updates. Rents ESTIMATED.",
  },
  {
    id: "sfr-237-w-1725n-cedar",
    source: "search",
    url: "https://www.zillow.com/cedar-city-ut/price-reduced/",
    name: "237 W 1725 N — 4bd (SUU)",
    address: "237 W 1725 N",
    city: "Cedar City",
    state: "UT",
    assetType: "house",
    beds: 4,
    sqft: 2016,
    price: 379900,
    priceCuts: "$10K cut (6/5)",
    driveHours: 0.8,
    stage: "sourced",
    fitScore: 6,
    contact: { brokerage: "ERA Realty", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "4/2-3, ~2,016 SF. SUU by-room: 4 × ~$525 ≈ $2,100/mo. Modest cut = seller only lightly motivated so far. Rents ESTIMATED; DOM unconfirmed.",
  },
  {
    id: "sfr-773-w-1050n-cedar",
    source: "search",
    url: "https://www.zillow.com/cedar-city-ut/price-reduced/",
    name: "773 W 1050 N — 3bd low entry (SUU)",
    address: "773 W 1050 N",
    city: "Cedar City",
    state: "UT",
    assetType: "house",
    beds: 3,
    sqft: 1100,
    price: 305900,
    priceCuts: "$4K cut (6/13) — token; room to negotiate",
    driveHours: 0.8,
    stage: "sourced",
    fitScore: 6,
    contact: { source: "Zillow price-reduced feed", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "3/2, ~1,100 SF — lowest entry among cut Cedar City SFRs. SUU by-room: 3 × ~$550 ≈ $1,650/mo. Smaller footprint = 3-room cap. Rents ESTIMATED; DOM unconfirmed.",
  },
  {
    id: "sfr-1074-king-richard-lv",
    source: "search",
    url: "https://www.zillow.com/las-vegas-nv/89119/price-reduced/",
    name: "1074 King Richard Ave — 3bd UNLV corridor",
    address: "1074 King Richard Ave",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 3,
    sqft: 1080,
    price: 349000,
    priceCuts: "$10K cut (6/26); ZIP 89119 −9.8% YoY",
    driveHours: 2,
    stage: "sourced",
    fitScore: 7,
    contact: { source: "Zillow 89119 price-reduced", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Standout Vegas value — whole ZIP 89119 down ~9.8% YoY = leverage. 3/2, ~1,080 SF, ~3mi UNLV. By-room: 3 × ~$700 ≈ $2,100/mo (rooms $825-1,420 in area; used conservative $700). Older/smaller = likely cosmetic fixer. Rents ESTIMATED.",
  },
  {
    id: "sfr-1995-kamber-lv",
    source: "search",
    url: "https://www.zillow.com/las-vegas-nv/89119/price-reduced/",
    name: "1995 Kamber Ct — 3bd UNLV corridor",
    address: "1995 Kamber Ct",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 3,
    sqft: 1576,
    price: 400000,
    priceCuts: "$20K cut (6/26)",
    driveHours: 2,
    stage: "sourced",
    fitScore: 6,
    contact: { source: "Zillow 89119 price-reduced", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Larger (3/2, ~1,576 SF) with more room to add value; same soft-ZIP tailwind (89119 −9.8% YoY). By-room: 3 × ~$700 ≈ $2,100/mo. Rents ESTIMATED; DOM unconfirmed.",
  },
  {
    id: "sfr-1442-harvest-moon-mesquite",
    source: "search",
    url: "https://www.zillow.com/mesquite-nv/price-reduced/",
    name: "1442 Harvest Moon Rdg — 2bd cash-flow",
    address: "1442 Harvest Moon Rdg",
    city: "Mesquite",
    state: "NV",
    assetType: "house",
    beds: 2,
    sqft: 1471,
    price: 292000,
    priceCuts: "$15K cut (6/29) — fresh",
    driveHours: 0.6,
    stage: "sourced",
    fitScore: 6,
    contact: { source: "Zillow Mesquite price-reduced", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "2/2, ~1,471 SF, fresh $15K cut. Mesquite is retiree/Sun City → whole-house cash-flow (~$1,600-1,800/mo), NOT student by-room. ~35 min from St George. Rents ESTIMATED.",
  },
  {
    id: "sfr-543-clark-mesquite",
    source: "search",
    url: "https://www.zillow.com/mesquite-nv/price-reduced/",
    name: "543 Clark St — 2bd small/motivated",
    address: "543 Clark St",
    city: "Mesquite",
    state: "NV",
    assetType: "house",
    beds: 2,
    sqft: 1040,
    price: 398000,
    priceCuts: "$16K cut (6/29)",
    driveHours: 0.6,
    stage: "sourced",
    fitScore: 5,
    contact: { source: "Zillow Mesquite price-reduced", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "2/2, ~1,040 SF, $16K cut. Small sqft for the price — whole-house ~$1,600/mo. Retiree market, not by-room. Rents ESTIMATED; DOM unconfirmed.",
  },
  {
    id: "sfr-2341-phoenix-kingman",
    source: "search",
    url: "https://www.coldwellbankerhomes.com/az/kingman/",
    name: "2341 Phoenix Ave — cheapest raw entry",
    address: "2341 Phoenix Ave",
    city: "Kingman",
    state: "AZ",
    assetType: "house",
    beds: 3,
    sqft: 1171,
    price: 225000,
    priceCuts: "Just listed (no cut) — value is low basis; Kingman median DOM ~55",
    driveHours: 2.5,
    stage: "sourced",
    fitScore: 6,
    contact: { source: "Coldwell Banker Kingman", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Cheapest raw entry in corridor. 3/2, ~1,171 SF, whole-house ~$1,500/mo. Kingman median fixer ~$324K so sub-$230K 3/2 is under-market. ~2.5-3h from St George. Value = low absolute basis, not a reduction. Also seen: 3225 N Central St $199,990 (2/2).",
  },
  {
    id: "sfr-2140-w-1610n-stgeorge",
    source: "search",
    url: "https://www.zillow.com/saint-george-ut/price-reduced/",
    name: "2140 W 1610 N — 4bd in-town (Utah Tech)",
    address: "2140 W 1610 N",
    city: "St. George",
    state: "UT",
    assetType: "house",
    beds: 4,
    sqft: 1875,
    price: 419000,
    priceCuts: "Price-reduced; below ~$520K St George avg",
    driveHours: 0,
    stage: "sourced",
    fitScore: 7,
    contact: { brokerage: "Real Broker LLC", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Rare St George 4-bed under $420K (avg home ~$520K). 4/2, ~1,875 SF; Utah Tech in-town for a by-room angle. Whole-house ~$2,200/mo. Verify cut size + condition. Rents ESTIMATED.",
  },

  // --- Las Vegas house-hack picks (live in one room/casita, rent the rest by-room to cover the payment) ---
  {
    id: "sfr-3462-huerta-lv",
    source: "search",
    url: "https://www.trulia.com/home/3462-huerta-dr-las-vegas-nv-89121-81827846",
    name: "3462 Huerta Dr — house-hack: 5bd main + 2bd casita, NO HOA",
    address: "3462 Huerta Dr",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 7,
    sqft: 2199,
    price: 295000,
    priceCuts: "Cut $298K → $295K (6/6); 82 DOM",
    driveHours: 2,
    stage: "sourced",
    fitScore: 9,
    sellerFinancing: false,
    contact: { name: "Monica Gomez", brokerage: "Signature Real Estate Group", phone: "(702) 268-2631", email: "MonicaGomezRealtor@gmail.com", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "★ TOP HOUSE-HACK PICK. 'Two houses on one lot,' NO HOA: main 5/2 (1,629 SF) + detached 2/1 casita (570 SF), fully renovated (new plumbing/elec/AC), RV parking, ~1970 build, UNLV-adjacent. Live in the casita (your + wife + Pomeranian spot), rent 5 main-house rooms by-room @ ~$700-800 ≈ $3,500-4,000/mo vs ~$1,800-1,900 payment → your spot FREE + ~$1,900/mo, and it still cash-flows half-empty. Seller financing NOT advertised but LIKELY (investor flip, 82 DOM, no HOA) — ASK. ⚠ Verify casita is legally permitted/separately metered + walk the east-side block in person. MLS 2645556/2771982. Rents ESTIMATED.",
  },
  {
    id: "sfr-3914-visby-lv",
    source: "search",
    url: "https://www.therivlingroup.com/las-vegas-financing-types/las-vegas-homes-w-owner-will-carry-financing-available/",
    name: "3914 Visby Ln — advertised owner-will-carry, UNLV zip 89119",
    address: "3914 Visby Ln",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 3,
    sqft: 1466,
    price: 215888,
    driveHours: 2,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: true,
    contact: { source: "The Rivlin Group owner-will-carry MLS filter", confidence: "medium" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "ADVERTISED OWNER-WILL-CARRY (on Rivlin Group's OWC-financing MLS filter). 3/2, 1,466 SF, $215,888 — cheapest of the set and in 89119, the actual UNLV zip (best by-room demand). Keep 1 room, rent 2 @ ~$700-800 ≈ $1,400-1,600 vs ~$1,200 P&I on a 7% carry → likely clears after taxes/HOA. ⚠ Visby/Swenson pocket is townhome-style = EXPECT AN HOA; confirm property type + that room-rentals are allowed (the load-bearing unknown) and get carry terms directly. Rents ESTIMATED.",
  },
  {
    id: "sfr-3211-sunrise-cove-lv",
    source: "search",
    url: "https://www.withroam.com/listing/3211-SUNRISE-COVE-AVE-NORTH-LAS-VEGAS-NV-89031/459208",
    name: "3211 Sunrise Cove Ave — assumable VA @ 2.75%",
    address: "3211 Sunrise Cove Ave",
    city: "North Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 3,
    sqft: 1385,
    price: 335000,
    driveHours: 2.1,
    stage: "sourced",
    fitScore: 7,
    sellerFinancing: true,
    contact: { name: "Kamyar Zargari", phone: "(702) 367-2323", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "ASSUMABLE VA LOAN @ 2.75% (verified on Roam): balance $263,057, payment $1,704/mo, cash gap ~$71,942, no second/gap loan. 3/2.5, 1,385 SF, built 2001, gated community w/ pool + solar. Keep 1 room, rent 2 @ ~$700-800 ≈ $1,400-1,600 → roughly breakeven vs the $1,704 payment; the prize is the locked 2.75% rate. Best structure: assume the low rate + ask seller to carry part of the ~$72K gap. ⚠ Gated/HOA = confirm room-rental rules before counting on by-room. Rents ESTIMATED.",
  },
  {
    id: "sfr-500-n-21st-lv",
    source: "search",
    url: "https://www.redfin.com/NV/Las-Vegas/500-N-21st-St-89101/home/29348946",
    name: "500 N 21st St — 7bd + casita, NO HOA (best cash-flow)",
    address: "500 N 21st St",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 7,
    sqft: 2284,
    yearBuilt: 1984,
    price: 505000,
    daysOnMarket: 84,
    priceCuts: "Listed 10/2025 at $519,777, cut 7× to $505,000 (~8 mo on market)",
    driveHours: 2,
    stage: "analyzed",
    fitScore: 9,
    sellerFinancing: false,
    contact: { name: "Angel G. Herrera", brokerage: "Perla Herrera Realty (listing agent)", phone: "(702) 816-0276", email: "angelherrerarealty@gmail.com", confidence: "high", source: "MLS #2771132" },
    analysis: {
      noi: 35036, capRate: 0.072, capex: 8000, stabilizedNoi: 45524, offerPrice: 488000, offerYieldOnCost: 0.072,
      fitScore: 9, model: "claude-opus-4-8", generatedAt: "2026-07-01T00:00:00Z",
      summary: "House-hack: owner lives in the casita, rents the 6-7 main-house bedrooms by the room. 6 rooms @ ~$775 ≈ a ~7% cap and +$544-994/mo cash flow while living free; full-rental ceiling ~11% cap. Seller is a stuck owner-occupant (bought the finished flip at $497K Jan-2025, ~8 mo on market, cut to $505K) → price/certainty play, not terms. The reno upside is already gone; you buy at ~ARV. Everything hinges on by-room legality (§7 of the report).",
      creativeTerms: "Seller has thin equity (bought Jan-2025), so a clean seller-carry is unlikely; the only creative angle is subject-to their existing loan + cash for their equity. Lead with a clean conventional close at a discount.",
      financing: [
        { label: "Owner-occupant conventional (recommended)", price: 488000, downPct: 0.15, rate: 0.0675, structure: "conventional", notes: "30-day clean close" },
        { label: "Fast cash-certainty", price: 472000, downPct: 1, rate: 0, structure: "cash", notes: "14-21 day close, minimal contingencies" },
        { label: "Seller-assisted / subject-to", price: 500000, downPct: 0.1, rate: 0.065, structure: "subject_to", notes: "take over their Jan-2025 note + cash for equity" },
      ],
      risks: [
        "BY-ROOM LEGALITY is the deciding risk — City of LV may treat 6 rooms/6 strangers as a rooming/boarding house (non-permitted in some SFR zones). Confirm zoning + licensing before offering.",
        "Casita may be an unfinished/unpermitted detached shell (photos) — you plan to LIVE in it; verify permit + finish.",
        "No garage, rooftop swamp cooler, chain-link/bare-dirt yard; reno is rental-grade cosmetic.",
        "Renovation value-add already captured by the prior flipper; downtown 89101 is the affordable, softer-rent core.",
      ],
    },
    offer: {
      recipient: "angelherrerarealty@gmail.com",
      subject: "Offer on 500 N 21st St — clean $488K close, flexible on your sellers' timeline",
      emailBody:
        "Hi Angel,\n\nI'd like to submit an offer on 500 N 21st St. I'm a local, owner-occupant buyer — I intend to live on the property — and I can close cleanly and quickly.\n\nPrimary offer: $488,000, conventional financing with a lender pre-approval, ~30-day close, as-is aside from a standard inspection. I'm happy to give your sellers flexible possession (up to a week rent-free after closing) to make their move easier. A full written LOI is attached.\n\nI know the home has been on the market a while — my goal is a smooth, certain close, not a drawn-out negotiation. I'm also flexible on structure: if the sellers want maximum speed I can look at a faster cash-style close, and if they'd like help on their end I'm open to a seller-assisted structure. Whatever works best for them.\n\nCould you let me know if the sellers are open to this, and share the disclosures, the solar details (owned vs. leased), and confirmation on the casita (permitted/finished)? I can turn a purchase agreement around within 48 hours.\n\nThank you,\n[Your name] · [phone] · [email]",
      status: "draft",
    },
    docs: [
      { label: "Full analysis report", url: "/reports/500-n-21st/report.html" },
      { label: "Landscaping options + budget", url: "/reports/500-n-21st/landscaping.html" },
      { label: "Offer / Letter of Intent", url: "/reports/500-n-21st/offer.html" },
      { label: "Direct-to-seller letter", url: "/reports/500-n-21st/seller-letter.html" },
    ],
    createdAt: "2026-07-01T00:00:00Z",
    notes: "★ Best by-room math of round 2. 7bd/3ba + separate casita, renovated, built 1984, SITE-BUILT, NO HOA, downtown 89101 (Medical District / UNLV med). Owner-occupant seller (Porras Orellano / Castro Chahua) bought the flip $497K Jan-2025, ~8 mo on market cut to $505K — motivated. Live in the casita, rent 6-7 rooms → ~7% house-hack cap, +$544-994/mo, live free. ⚠ DECIDING RISK: by-room legality (City of LV rooming-house rules) + casita permit/finish. See hosted report. Rents ESTIMATED.",
  },
  {
    id: "sfr-2856-natalie-lv",
    source: "search",
    url: "https://www.zillow.com/homedetails/2856-Natalie-Ave-Las-Vegas-NV-89121/",
    name: "2856 Natalie Ave — 7bd near UNLV (best profit engine)",
    address: "2856 Natalie Ave",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 7,
    sqft: 2259,
    price: 550000,
    priceCuts: "Fresh listing (6 DOM) — no motivation lever yet; lowball candidate",
    driveHours: 2,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: false,
    contact: { source: "verify agent (MLS via SeeVegasHomes/TotalVegas IDX)", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Strongest raw by-room engine near UNLV: 7bd/3ba/2,259 SF, SITE-BUILT, UNLV-adjacent 89121. No casita, so keep 1 bedroom, rent 6 @ ~$750 ≈ $4,500 vs ~$3,250 payment → FREE + ~$1,250/mo. Only 6 DOM (not motivated yet) — watch/lowball. Rents ESTIMATED; confirm agent + HOA + room-rental legality.",
  },
  {
    id: "sfr-1729-griffith-lv",
    source: "search",
    url: "https://www.redfin.com/NV/Las-Vegas/1729-Griffith-Ave-89104/home/29452912",
    name: "1729 Griffith Ave — true detached casita (own kitchen+bath)",
    address: "1729 Griffith Ave",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 4,
    sqft: 2029,
    price: 449900,
    daysOnMarket: 17,
    driveHours: 2,
    stage: "sourced",
    fitScore: 8,
    sellerFinancing: false,
    contact: { name: "Justin E. Simmons", brokerage: "Realty One Group", phone: "(702) 898-7575", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Best casita QUALITY of the set: detached casita with its OWN kitchenette + full bath (a true rentable unit), main house 3bd/2ba + den, built 1961, SITE-BUILT, UNLV-adjacent 89104, likely no HOA (verify). Keep casita, rent 4 rooms @ ~$750 ≈ $3,000 vs ~$2,835 → +$165; better: keep a room + rent the casita → ~+$565/mo. Cheapest true-casita entry. MLS 2784797. Rents ESTIMATED.",
  },
  {
    id: "sfr-4185-vancouver-lv",
    source: "search",
    url: "https://www.zillow.com/homedetails/4185-Vancouver-Ave-Las-Vegas-NV-89121/",
    name: "4185 Vancouver Ave — 5bd + casita, UNLV zip",
    address: "4185 Vancouver Ave",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 5,
    sqft: 2110,
    price: 549888,
    driveHours: 2,
    stage: "sourced",
    fitScore: 7,
    sellerFinancing: false,
    contact: { source: "MLS 2791822 (El Encanto)", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "5bd + casita in UNLV zip 89121 (El Encanto tract), site-built likely. Keep casita, rent 5 rooms @ ~$750 ≈ $3,750 vs ~$3,355 → FREE + ~$395/mo. ⚠ Detached-vs-attached casita unconfirmed; verify casita type, site-built, agent (MLS 2791822), HOA. Rents ESTIMATED.",
  },
  {
    id: "sfr-700-s-mallard-lv",
    source: "search",
    url: "https://www.zillow.com/homedetails/700-S-Mallard-St-Las-Vegas-NV-89107/",
    name: "700 S Mallard St — 4bd + casita, cheapest positive",
    address: "700 S Mallard St",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 4,
    sqft: 1202,
    price: 419500,
    daysOnMarket: 53,
    driveHours: 2,
    stage: "sourced",
    fitScore: 7,
    sellerFinancing: false,
    contact: { source: "verify agent (SeeVegasHomes IDX)", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Cheapest positive-cashflow casita option. 4bd/2ba + casita, SITE-BUILT, central LV 89107 (partial UNLV demand), 53 DOM. Keep casita, rent 4 rooms @ ~$700 ≈ $2,800 vs ~$2,450 → FREE + ~$350/mo. Small (1,202 SF) so rooms are modest. ⚠ Verify casita permitted + HOA + room-rental rules. Rents ESTIMATED.",
  },
  {
    id: "sfr-3116-kings-way-lv",
    source: "search",
    url: "https://www.zillow.com/homedetails/3116-Kings-Way-Las-Vegas-NV-89102/7084778_zpid/",
    name: "3116 Kings Way — 5bd, owner-carry eligible (best cash-flow, verify)",
    address: "3116 Kings Way",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 5,
    sqft: 1434,
    price: 350000,
    driveHours: 2,
    stage: "sourced",
    fitScore: 7,
    sellerFinancing: true,
    contact: { source: "The Rivlin Group AITD/OWC feed; MLS 2791719", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "On Rivlin Group's AITD / owner-will-carry-ELIGIBLE feed (carry advertised NOT yet confirmed). 5bd/2.75ba, central LV 89102. IF price/carry check out, best by-room cash-flow found: keep 1 room, rent 4 @ ~$700 ≈ $2,800 vs $1,430-2,240 payment → +$560 to +$1,370/mo. ⚠ HEAVY VERIFY: price disputed ($219K Rivlin feed vs ~$350K search — used $350K), confirm owner-carry is truly offered, that it's site-built (not a conversion), and that 5bd/1,434 SF are LEGAL bedrooms. Rents ESTIMATED.",
  },
  {
    id: "sfr-4437-panoramic-nlv",
    source: "search",
    url: "https://www.seevegashomes.com/north-las-vegas-homes-with-casita/",
    name: "4437 Panoramic View Ave — casita, 81 DOM (stalest = carry ask)",
    address: "4437 Panoramic View Ave",
    city: "North Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 4,
    sqft: 2474,
    price: 599000,
    daysOnMarket: 81,
    driveHours: 2.2,
    stage: "sourced",
    fitScore: 6,
    sellerFinancing: false,
    contact: { source: "verify agent (Valley Vista tract; IDX)", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "STALEST of the batch at 81 DOM (52-day-avg market) → best motivated-seller / seller-finance ASK target. 4bd/3.5ba + casita, SITE-BUILT (Valley Vista). Far-N (weak UNLV demand). Keep casita empty → ~-$700/mo; rent the casita too (~$900) → ~+$200/mo. ⚠ Master-planned HOA — confirm room-rental/short-stay rules BEFORE offering. Use the long DOM as leverage for a price cut or carry. Rents ESTIMATED.",
  },
  {
    id: "sfr-4420-cityscape-nlv",
    source: "search",
    url: "https://www.seevegashomes.com/north-las-vegas-homes-with-casita/",
    name: "4420 Cityscape Glen Ct — casita, 76 DOM (bigger value)",
    address: "4420 Cityscape Glen Ct",
    city: "North Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 4,
    sqft: 2958,
    price: 595000,
    daysOnMarket: 76,
    driveHours: 2.2,
    stage: "sourced",
    fitScore: 6,
    sellerFinancing: false,
    contact: { source: "verify agent (Valley Vista tract; IDX)", confidence: "low" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Same Valley Vista tract/economics as 4437 Panoramic but BIGGER (2,958 SF) for $4K less = better value; 76 DOM (motivated). 4bd/3.5ba + casita, SITE-BUILT. Far-N (weak UNLV). Works best as keep-a-room + rent-the-casita. ⚠ Same HOA room-rental caveat. Rents ESTIMATED.",
  },
  {
    id: "sfr-2196-pescara-lv",
    source: "search",
    url: "https://www.redfin.com/NV/Las-Vegas/2196-Pescara-Ct-89123/home/29634131",
    name: "2196 Pescara Ct — 5bd, ADVERTISED seller carry (motivated)",
    address: "2196 Pescara Ct",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 5,
    sqft: 2792,
    price: 699000,
    priceCuts: "Churn: sold $530K (2022), listed $689K/$670K, now $699K relisted — motivated",
    driveHours: 2,
    stage: "sourced",
    fitScore: 6,
    sellerFinancing: true,
    contact: { name: "Rochanna Ghafouria", brokerage: "The Collection", phone: "(702) 874-8555", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "ADVERTISED SELLER CARRY: listing says 'purchase through creative seller financing — no banks, no strict qualifications' (terms open). 5bd/3ba/2,792, built 1998, SITE-BUILT, HOA $13/mo, pool+spa, SE/Silverado (not UNLV). Long failed-sale history = motivated → push for a LOW/zero-interest carry. At list the by-room math is ~-$1,170/mo, so ONLY works if you negotiate the carry rate down hard (or run as STR, how it's marketed). MLS 2796255. Rents ESTIMATED.",
  },
  {
    id: "sfr-3480-hacienda-lv",
    source: "search",
    url: "https://www.redfin.com/NV/Las-Vegas/3480-E-Hacienda-Ave-89120/home/29442390",
    name: "3480 E Hacienda Ave — premium detached casita + pool, NO HOA",
    address: "3480 E Hacienda Ave",
    city: "Las Vegas",
    state: "NV",
    assetType: "house",
    beds: 4,
    sqft: 2622,
    price: 599900,
    driveHours: 2,
    stage: "sourced",
    fitScore: 6,
    sellerFinancing: false,
    contact: { name: "Angel & Linda Bothof", phone: "(702) 524-8161", confidence: "high" },
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Best casita PRODUCT: large detached live-in guest-house casita + pool, one-story on a ¼-acre, NO HOA, 89120 (airport/UNLV-ish). Priced at $599,900 so the math works as keep-a-room + rent-the-big-casita (~$1,300) → roughly breakeven; the appeal is a genuinely nice personal casita with no HOA. MLS 2745380. Rents ESTIMATED; verify DOM/motivation.",
  },
];
